### ISSUE TITLE
Question about evaluating BARD

### ISSUE THREAD

**Issue by vishaal27** [yuweihao/MM-Vet#1]
How do you evaluate BARD on your dataset? Do you manually input the questions, or do you have a API you access? It would be much appreciated if you could share your BARD inference scripts, thanks!

**Comment by yuweihao** [comment]
Hi @vishaal27 ,

Thanks for your attention to our work. We use an unofficial API [Bard-API](https://github.com/dsdanielpark/Bard-API#bard-ask_about_image-method). For the Bard inference script, I will arrange it and release it in 2 or 3 days.

**Comment by yuweihao** [comment]
Hi @vishaal27 

For Bard inference script, please refer these two files: [inference_bard.py](https://github.com/yuweihao/MM-Vet/blob/main/misc/inference_bard.py) and [inference_bard.sh](https://github.com/yuweihao/MM-Vet/blob/main/misc/inference_bard.sh).
