### ISSUE TITLE
Please evaluate Otter-MPT7B version instead of Llama7B version

### ISSUE THREAD

**Issue by Luodian** [yuweihao/MM-Vet#2]
Thanks for the wonderful evaluation work!
But the Otter evaluation seems based on our early version (around May 2023), we have a stronger MPT7B version Otter since last month based on OpenFlamingoV2. Would you like to try to evaluate it instead of the LLama7B version.

Both OpenFlamingoV2 and Otter-MPT7B have much better performance than previous version. Please consider using them to rejustify the evaluation results.

We also have a video version of Otter, would you like to add it to further VideoLLM evaluation?

Otter-Image: https://huggingface.co/luodian/OTTER-Image-MPT7B
Otter-Video: https://huggingface.co/luodian/OTTER-Video-LLaMA7B-DenseCaption

**Comment by yuweihao** [comment]
Hi @Luodian ,

Thank you so much for your attention. Your work Otter is wonderful and I really like it. Yes, the Otter we evaluated is the old version where the LLM is LLaMa-7B. Thanks for your update, we will git clone the latest code and model of Otter (based on OpenFlamingoV2 where LLM is MPT-7B) to conduct the evaluation. The results will be updated in the next arXiv version. 

For the video version of Otter, we are very glad to add it when MM-Vet supports videos in the future.

**Comment by Luodian** [comment]
Thanks and you can evaluate with the guideline demo. We use <image> and <answer> as special token during training, the format is:
```
otter_template = f"<image>User: {instruction} GPT:<answer>"
```

Details: https://github.com/Luodian/Otter/blob/main/pipeline/demo/otter_image.py

For OF-v2, the template is simpler, you could evaluate with the <image> + instruction.
`<image> an image of` or `<image> what does the image describe?`

I also privately ping Anas (the first author of OpenFlamingo) this issue and he may check the details of prompt template.

**Comment by yuweihao** [comment]
Hi @Luodian , Thanks for your detailed guideline. MM-Vet currently only supports zero-shot setting. 

Yes, for Otter based on OpenFlamingo V1, we use the prompt template as you show:
```python
f"<image>User: {a_question_of_MM_Vet} GPT:<answer>
```

For OF-v2, can I confirms the template will be as follows for MM-Vet?
```python
f"<image> {a_question_of_MM_Vet}"
```

Thank you so much.

**Comment by Luodian** [comment]
The first template can be used to Otter-MPT version as well. The second version can be used to OF-v2.

**Comment by anas-awadalla** [comment]
Hello! Anas from OpenFlamingo here. We don't have a space between the <image> and the text. I think the template should be:

> f"<image> {a_question_of_MM_Vet}"

Thank you for your awesome work!!

**Comment by yuweihao** [comment]
Hi @Luodian , thanks for the clarification. 

Hi @anas-awadalla , thanks for your great contribution of OpenFlamingo to research community. In the paper arXiv v1, the results of OpenFlamingo are obtained by the prompt template:
```python
f'<image>Question: {a_question_of_MM_Vet} Answer:'
```
and use
```python
open_flamingo_output.split('Question:')[0].strip()
```
to filter the results.

Thanks for your guidance. We will try the new prompt template and the new OpenFlamingo model.

**Comment by anas-awadalla** [comment]
Cool! I think I originally mistyped before but this prompt format looks great!
