### ISSUE TITLE
Evaluating GPT-4V

### ISSUE THREAD

**Issue by anselmwang** [yuweihao/MM-Vet#4]
Would you mind to share your GPT-4V inference and evaluation script? Really appreciate your help.
I have tried by myself, and only achieve score 61.8, far from 67.7.

```
        rec   ocr  know   gen  spat  math  total  std    runs
gpt4v  54.8  74.1  39.6  42.9  74.7  75.2   61.8  0.0  [61.8]
       know_gen_rec   rec  spat_ocr  math_spat_ocr  spat_rec   ocr  math_ocr  know_rec  know_ocr_gen_rec  ...  spat_ocr_rec  ocr_rec  know_spat_ocr  spat_know_rec  spat_ocr_gen  math_spat_ocr_rec  total  std    runs
gpt4v          33.9  81.1      79.6           92.1      66.7  73.3      59.0      27.8              71.2  ...          42.9    100.0           66.7          100.0          85.0                0.0   61.8  0.0  [61.8]
```

**Comment by yuweihao** [comment]
Hi Yu

Thanks for your attention. Thanks to Dr Zhengyuan Yang (@zyang-ur ) for conducting the GPT-4V experiments on MM-Vet. I just cleaned and uploaded the inference script. Please see https://github.com/yuweihao/MM-Vet/blob/main/misc/inference_gpt4v.py.

**Comment by anselmwang** [comment]
Thanks @yuweihao  . It works!
