### ISSUE TITLE
server is down

### ISSUE THREAD

**Issue by pipilurj** [yuweihao/MM-Vet#6]
Hi, thanks very much for the contribution! However, the huggingface space seems to be down. Could you please check? Thanks!

**Comment by yuweihao** [comment]
Hi @pipilurj , I just use this json [example](https://raw.githubusercontent.com/yuweihao/MM-Vet/main/results/llava_llama2_13b_chat.json) to test and find the online evaluator on Huggingface still works. Could you please check your json format, like the dict key name?
