### ISSUE TITLE
Link for v2 Leaderboard is broken

### ISSUE THREAD

**Issue by NotTheD** [yuweihao/MM-Vet#7]
Hi!
Link for leadervord for v2 pointed to paperswithcode.com is 404.

**Comment by yuweihao** [comment]
Hi @NotTheD , thank you for your attention. We are waiting for paperswithcode to add our MM-Vet v2 paper and then create the leaderboard. Currently, it seems paperswithcode is only updating papers until 30 July 2024.

**Comment by NotTheD** [comment]
Thx for reaction! Hope PWC do it shortly.
Cheers for awesome benchmark! Keep doing it!

**Comment by yuweihao** [comment]
Hi NotTheD, the leaderboard of MM-Vet v2 on PWC works now https://paperswithcode.com/sota/visual-question-answering-on-mm-vet-v2.
