### ISSUE TITLE
Make MM-Vet available as a HF dataset

### ISSUE THREAD

**Issue by NielsRogge** [yuweihao/MM-Vet#8]
Hi there,

Congrats on your work. I discovered it through the paper page: https://huggingface.co/papers/2408.00765. I see the paper already has a linked Space, it would be great to also make the benchmark available as a 🤗 Dataset, enabling people to load the data in 2 lines of code:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-organization/mm-vet")
```
This also comes with a dataset viewer, enabling people to see the first few rows in the browser.

See for instance these multimodal datasets as examples:

- https://huggingface.co/datasets/xai-org/RealworldQA
- https://huggingface.co/datasets/nielsr/docvqa_1200_examples_donut

This could perhaps be made available as part of the National University of Singapore organization: https://huggingface.co/NationalUniversityofSingapore.

Let me know if you need any help regarding this!

Cheers,

Niels
Open-source @ HF

**Comment by yuweihao** [comment]
Hi Niels,

Thanks for the helpful materials. Currently, I am busy with the rebuttal for a paper submission. I will complete it in a week. Thanks a lot.

**Comment by yuweihao** [comment]
Hi Niels, thanks, we have uploaded MM-Vet to Hugging Face https://huggingface.co/datasets/whyu/mm-vet.

**Comment by NielsRogge** [comment]
Thanks a lot! I also opened a PR to link it to the paper page: https://huggingface.co/datasets/whyu/mm-vet/discussions/2

**Comment by yuweihao** [comment]
Hi @NielsRogge , thank you so much. I have merged it and I also uploaded v2 to Hugging Face:

MM-Vet: https://huggingface.co/datasets/whyu/mm-vet

MM-Vet v2: https://huggingface.co/datasets/whyu/mm-vet-v2
